export const BASE_URL = process.env.PUBLIC_URL;
export * from './navigation/navigation';
export * from './intro/intro';
export * from './about/about';
export * from './more/more';
export * from './get-iwi/get-iwi';
export * from './newsletter/newsletter';
export * from './social-media-icons/social-media-icons';
export * from './footer/footer';
export * from './privacy-policy-content/privacy-policy-content';